[package]
name = "rust-ws-http"
version = "0.1.0"
edition = "2021"
description = "WebSocket proxy toolkit (WASM compatible)"

[dependencies]
# Workspace dependencies
base64 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

# Local dependencies
rust-ws-core = { path = "../rust-ws-core" }
